doing homework 20
Hromy-Ann/aqa-hillel-practice-software-testing pull request #3
Opened 2024-07-07 17:49 UTC by Hromy-Ann

2024-07-07 19:34 UTC, alexshamrai requested changes

2024-07-07 19:34 UTC, alexshamrai commented on src/main/java/com/practicesoftwaretesting/cart/asserts/UpdateCartResponseAsserts.java
> +    private final UpdateCartResponse actual;
```suggestion

    private final UpdateCartResponse actual;
```

2024-07-07 19:34 UTC, alexshamrai commented on src/main/java/com/practicesoftwaretesting/cart/asserts/CreateCartResponseAsserts.java
> +    public CreateCartResponseAsserts hasSomeId() {
```suggestion
    public CreateCartResponseAsserts idIsNotNull() {
```
or `hasValidId`

2024-07-14 15:12 UTC, Hromy-Ann commented on src/main/java/com/practicesoftwaretesting/cart/asserts/UpdateCartResponseAsserts.java
> +    private final UpdateCartResponse actual;
fixed

2024-07-14 15:12 UTC, Hromy-Ann commented on src/main/java/com/practicesoftwaretesting/cart/asserts/CreateCartResponseAsserts.java
> +    public CreateCartResponseAsserts hasSomeId() {
fixed

2024-07-14 15:53 UTC, alexshamrai approved these changes

2024-07-14 16:47 UTC, merged